/* 
  Sketch generated by the Arduino IoT Cloud Thing "Bin One"
  https://create.arduino.cc/cloud/things/acdff5db-845e-42f4-851d-6b8367a3c258 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temperature1;
  float temperature3;
  float temperature2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DHT.h>
#include <DHT_U.h>
#include <Adafruit_Sensor.h>

// everything to control the sensors
#define DHTPIN1            5
#define DHTPIN2            4
#define DHTPIN3            6

#define DHTTYPE           DHT22

DHT_Unified dht1(DHTPIN1, DHTTYPE);
DHT_Unified dht2(DHTPIN2, DHTTYPE);
DHT_Unified dht3(DHTPIN3, DHTTYPE);

unsigned long count;

int resetPin = 1;

void setup() {
  digitalWrite(resetPin, HIGH);
  pinMode(resetPin, OUTPUT); 
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  ArduinoCloud.addCallback(ArduinoIoTCloudEvent::DISCONNECT, doThisOnDisconnect);
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  dht1.begin();
  dht2.begin();
  dht3.begin();

  sensor_t sensor;
  
  count = 0;
}


void loop() {
  delay(500);
  ArduinoCloud.update();
  // Your code here 
  
  if (count < millis()){
    // Get temperature event
    sensors_event_t event1;
    dht1.temperature().getEvent(&event1);
    
    if (isnan(event1.temperature)) {
      temperature1 = -100.0;
    }
    else {
      temperature1 = event1.temperature;
    }
    
    // Get temperature event
    sensors_event_t event2;
    dht2.temperature().getEvent(&event2);
    
    if (isnan(event2.temperature)) {
      temperature2 = -100.0;
    }
    else {
      temperature2 = event2.temperature;
    }
    
    // Get temperature event
    sensors_event_t event3;
    dht3.temperature().getEvent(&event3);
    
    if (isnan(event3.temperature)) {
      temperature3 = -100.0;
    }
    else {
      temperature3 = event3.temperature;
    }
    
    count = millis() + 900000;
  }
}

void doThisOnDisconnect(){
  /* add your custom code here */
  Serial.println("Board disconnected from Arduino IoT Cloud");
  
  delay(60000);
  
  digitalWrite(resetPin, LOW);
}