/// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]      = "acdff5db-845e-42f4-851d-6b8367a3c258";

const char GPRS_APN[]      = SECRET_APN;
const char PINNUMBER[]     = SECRET_PIN;
const char GPRS_LOGIN[]    = SECRET_USERNAME;
const char GPRS_PASSWORD[] = SECRET_PASSWORD;


float temperature1;
float temperature3;
float temperature2;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(temperature1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature2, READ, ON_CHANGE, NULL);

}

GSMConnectionHandler ArduinoIoTPreferredConnection(PINNUMBER, GPRS_APN, GPRS_LOGIN, GPRS_PASSWORD);