// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "952e3ad9-ef0f-46b0-aa63-a71ab33f7a11";

const char SSID[]     = "";    // Network SSID (name)
const char PASS[]     = "";    // Network password (use for WPA, or use as key for WEP)


float one_top;
float one_bottom;
float one_middle;
float two_middle;
float two_top;
float two_bottom;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(one_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(one_bottom, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(one_middle, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(two_middle, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(two_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(two_bottom, READ, 900 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
