// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]      = "thing-id-goes-here";

const char SSID[]     = "network-name-goes-here";    // Network SSID (name)
const char PASS[]     = "network-password-goes-here";    // Network password (use for WPA, or use as key for WEP)

float pcb_temp;

float one_top;
float one_middle_bottom;
float one_middle_top;
float one_bottom;

float two_top;
float two_middle_top;
float two_middle_bottom;
float two_bottom;

float three_top;
float three_middle_top;
float three_middle_bottom;
float three_bottom;

float four_top;
float four_middle_top;
float four_middle_bottom;
float four_bottom;



void initProperties(){

  ArduinoCloud.setThingId(THING_ID);

  ArduinoCloud.addProperty(pcb_temp, READ, 900 * SECONDS, NULL);

  ArduinoCloud.addProperty(one_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(one_middle_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(one_middle_bottom, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(one_bottom, READ, 900 * SECONDS, NULL);

  ArduinoCloud.addProperty(two_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(two_middle_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(two_middle_bottom, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(two_bottom, READ, 900 * SECONDS, NULL);

  ArduinoCloud.addProperty(three_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(three_middle_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(three_middle_bottom, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(three_bottom, READ, 900 * SECONDS, NULL);

  ArduinoCloud.addProperty(four_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(four_middle_top, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(four_middle_bottom, READ, 900 * SECONDS, NULL);
  ArduinoCloud.addProperty(four_bottom, READ, 900 * SECONDS, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
